name: Bug Report
description: Signaler un bug ou un probleme
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Merci de prendre le temps de signaler ce bug!
        Veuillez remplir le formulaire ci-dessous pour nous aider a reproduire et corriger le probleme.

  - type: textarea
    id: description
    attributes:
      label: Description du bug
      description: Une description claire et concise du bug
      placeholder: "Ex: L'application plante quand je clique sur le bouton 'Sauvegarder'"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Etapes pour reproduire
      description: Les etapes pour reproduire le comportement
      placeholder: |
        1. Aller sur '...'
        2. Cliquer sur '...'
        3. Faire defiler jusqu'a '...'
        4. Voir l'erreur
      value: |
        1.
        2.
        3.
        4.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Comportement attendu
      description: Une description claire et concise de ce qui devrait se passer
      placeholder: "Ex: Le formulaire devrait etre sauvegarde et afficher un message de succes"
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Comportement actuel
      description: Une description claire et concise de ce qui se passe reellement
      placeholder: "Ex: L'application plante avec l'erreur 'Cannot read property...'"
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Captures d'ecran
      description: Si applicable, ajoutez des captures d'ecran pour aider a expliquer le probleme
      placeholder: Glissez-deposez vos images ici ou collez-les

  - type: dropdown
    id: browser
    attributes:
      label: Navigateur
      description: Sur quel navigateur avez-vous rencontre ce probleme?
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Autre (preciser dans les infos supplementaires)
      multiple: true
    validations:
      required: true

  - type: input
    id: browser-version
    attributes:
      label: Version du navigateur
      description: Quelle version du navigateur utilisez-vous?
      placeholder: "Ex: Chrome 120.0.6099.109"

  - type: dropdown
    id: os
    attributes:
      label: Systeme d'exploitation
      description: Sur quel systeme d'exploitation avez-vous rencontre ce probleme?
      options:
        - Windows
        - macOS
        - Linux
        - iOS
        - Android
        - Autre (preciser dans les infos supplementaires)
    validations:
      required: true

  - type: input
    id: os-version
    attributes:
      label: Version du systeme d'exploitation
      description: Quelle version du systeme d'exploitation utilisez-vous?
      placeholder: "Ex: Windows 11, macOS 14.1, Ubuntu 22.04"

  - type: dropdown
    id: device
    attributes:
      label: Type d'appareil
      description: Sur quel type d'appareil avez-vous rencontre ce probleme?
      options:
        - Desktop
        - Mobile
        - Tablette
    validations:
      required: true

  - type: textarea
    id: console-errors
    attributes:
      label: Erreurs de console
      description: Copiez-collez toutes les erreurs de la console JavaScript (F12 > Console)
      render: shell
      placeholder: |
        Uncaught TypeError: Cannot read property 'xxx' of undefined
            at Component.tsx:42

  - type: dropdown
    id: severity
    attributes:
      label: Severite
      description: Quelle est la severite de ce bug?
      options:
        - Critique (l'application ne peut pas etre utilisee)
        - Majeure (fonctionnalite importante cassee)
        - Mineure (probleme cosmetique ou workaround disponible)
        - Triviale (suggestion d'amelioration)
    validations:
      required: true

  - type: dropdown
    id: frequency
    attributes:
      label: Frequence
      description: A quelle frequence ce bug se produit-il?
      options:
        - Toujours (100%)
        - Frequemment (>50%)
        - Parfois (10-50%)
        - Rarement (<10%)
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Informations supplementaires
      description: Tout autre contexte pertinent sur le probleme
      placeholder: |
        - L'erreur se produit uniquement avec certains comptes utilisateur
        - Le probleme a commence apres la derniere mise a jour
        - Etc.

  - type: checkboxes
    id: terms
    attributes:
      label: Verification
      description: Veuillez confirmer les elements suivants
      options:
        - label: J'ai verifie qu'il n'y a pas de probleme similaire deja rapporte
          required: true
        - label: J'ai verifie que ce probleme n'est pas deja resolu dans la derniere version
          required: true
        - label: J'ai fourni toutes les informations necessaires pour reproduire le probleme
          required: true
